### PR TITLE
added upstart compatibility

### PR DESCRIPTION
**Pull request by ZyanKLee**
* new templates/upstart.erb
* changed manifests/install.pp to switch path and template
  when service_provider == upstart

Not resolved:
* did not add spec's as I don't know how to do this

### CODE REVIEW

**Comment by danielsreichenbach** [comment]
Thanks for your pull request!

Can you elaborate for which operating systems / OS families you'd want to use Upstart? There might be a much simpler solution to this without requiring changes to the Puppet code, since we're on Puppet 4+ and use Hiera data to supply configuration.

Thus we could e.g. update `hiera.yml` to add a layer based on OS family, or even OS name and version if needed and using that supply a different `service_path` and `service_provider` value for when Upstart is used instead of systemd.

**Comment by ZyanKLee** [comment]
thanks for your reply.
Upstart support is needed for Ubuntu 14.04 lts aka trusty. From 16.04
systemd is being used by default.

>

**Comment by ZyanKLee** [comment]
you are right about the point that changing the code is not needed. adding the template and setting service_template within hiera should work as well and is easier to maintain.

**Comment by danielsreichenbach** [comment]
Do you want to submit the Hiera changes? If not, I can do that later today and push out an update release.

**Comment by ZyanKLee** [comment]
I can do so, but am AFK at the moment and won't be able to do this until tonight at the earliest. Feel free to go ahead.

**Comment by ZyanKLee** [comment]
Imho, this PR can/should be closed. As we discussed a long time ago, my first attempt at solving the issue is not recommendable anymore.
I changed to a new employer since creating this PR and don't know, when I will find the time to fix this properly.

**Pull request closed without merging**
